name: Deploy
on: [push, pull_request]
  # manual trigger
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd ./packages/type-definitions/ && npm install

      - name: Tests pass
        run: npm test

      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@18351461ae08dde235c0ccee0633ec905f0b9a52
        with:
          token: ${{ secrets.NPM_TOKEN }}